// FrontEnd/Angular/quicktoolhub-frontend/src/app/shared/components/tool-card/tool-card.component.ts
import { Component, input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ToolDefinition } from '../../../core/models/tool.model';

@Component({
  selector: 'app-tool-card',
  imports: [RouterLink],
  templateUrl: './tool-card.component.html',
})
export class ToolCardComponent {
  readonly tool = input.required<ToolDefinition>();
}

<a
  [routerLink]="['/tools', tool().slug]"
  class="group flex h-full flex-col rounded-2xl bg-[var(--panel)] p-1 shadow-[0_24px_65px_-52px_rgb(0_0_0/80%)] ring-1 ring-[var(--border)] transition duration-500 ease-[cubic-bezier(0.32,0.72,0,1)] hover:-translate-y-1 hover:bg-[var(--panel-hover)] hover:ring-[var(--border-hover)]"
>
  <div class="flex h-full flex-col rounded-[0.85rem] bg-[var(--panel-strong)] p-5 shadow-[inset_0_1px_0_rgba(255,255,255,0.08)]">
    <div class="mb-5 flex items-center justify-between">
      <span class="grid size-11 place-items-center rounded-xl bg-[var(--accent)] text-xs font-black text-white shadow-[inset_0_1px_0_rgba(255,255,255,0.24)]">{{ tool().icon }}</span>
      <span class="rounded-lg bg-[var(--accent-soft)] px-2.5 py-1 text-xs font-semibold text-[var(--accent-strong)] ring-1 ring-[var(--border)]">{{ tool().category }}</span>
    </div>
    <h2 class="text-lg font-semibold text-[var(--foreground)] transition group-hover:text-[var(--accent-strong)]">{{ tool().name }}</h2>
    <p class="mt-3 flex-1 text-sm leading-6 text-[var(--muted)]">{{ tool().description }}</p>
    <span class="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[var(--foreground)]">
      Open tool
      <span class="grid size-6 place-items-center rounded-lg bg-[var(--panel-hover)] text-xs transition group-hover:translate-x-1 group-hover:bg-[var(--accent)] group-hover:text-white">-></span>
    </span>
  </div>
</a>

// toolnest-web/components/tools/tool-card.tsx
import Link from "next/link";
import { Users } from "lucide-react";
import { getCategory, Tool, toolIcons } from "@/lib/tools";

export function ToolCard({ tool }: { tool: Tool }) {
  const Icon = toolIcons[tool.icon];
  const category = getCategory(tool.categorySlug);

  return (
    <Link
      href={`/tools/${tool.slug}`}
      className="tn-card group block p-4 transition hover:border-[var(--border-primary)] hover:shadow-sm"
    >
      <div className="flex items-start gap-3">
        <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-[var(--accent-soft)] text-[var(--accent)]">
          <Icon size={18} strokeWidth={1.8} />
        </div>
        <div className="min-w-0 flex-1">
          <h3 className="truncate text-sm font-semibold text-[var(--text-primary)] group-hover:text-[var(--accent)]">{tool.name}</h3>
          <p className="mt-1 line-clamp-2 text-xs leading-5 text-[var(--text-secondary)]">{tool.tagline}</p>
        </div>
      </div>
      <div className="mt-3 flex items-center gap-2">
        <span className="rounded-full bg-[var(--accent-soft)] px-2 py-0.5 text-[10px] font-medium text-[var(--accent)]">
          {category?.name.replace(" tools", "")}
        </span>
        {tool.isNew ? <span className="rounded-full bg-[#eaf3de] px-2 py-0.5 text-[10px] font-medium text-[#27500a]">New</span> : null}
        {tool.isFeatured ? <span className="rounded-full bg-[#e6f1fb] px-2 py-0.5 text-[10px] font-medium text-[#0c447c]">Hot</span> : null}
        <span className="ml-auto flex items-center gap-1 text-[10px] text-[var(--text-tertiary)]">
          <Users size={11} strokeWidth={1.8} />
          {(tool.usageCount / 1000).toFixed(1)}K
        </span>
      </div>
    </Link>
  );
}
